# Generated by Django 5.1 on 2024-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('reading', 'Reading')], max_length=10)),
                ('year', models.DateField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
            ],
        ),
    ]
