# Generated by Django 5.1 on 2024-08-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookCategory',
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
